baseurl = "http://simonwillshire.com/"
languageCode = "en-us"
title = "Simon Willshire"
copyright = ""
relativeURLs = true
canonifyURLs = true
paginate = 10
author = "Simon Willshire"
publishdir = "public"
disqusShortname = "simonwillshire"
